width = 393;
height = 852;

export const tasks = [
  {
    name: "The Logo Process",
    progress: 0,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "High",
    status: "in progress",
    category: "design",
  },
  {
    name: "Design of the day challenge",
    progress: 60,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "Medium",
    status: "completed",
    category: "design",
  },
  {
    name: "Watch Anime",
    progress: 10,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "Low",
    status: "to do",
    category: "Leisure",
  },
  {
    name: "Make Money",
    progress: 60,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "High",
    status: "in progress",
    category: "Career",
  },
  {
    name: "Wash cloth",
    progress: 100,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "Medium",
    status: "completed",
    category: "House Works",
  },
  {
    name: "Eat Sharwama",
    progress: 30,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "High",
    status: "to do",
    category: "Food",
  },
  {
    name: "Studying figma",
    progress: 80,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "High",
    status: "in progress",
    category: "design",
  },
  {
    name: "Going on outing",
    progress: 50,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "High",
    status: "in progress",
    category: "Rest",
  },
  {
    name: "Reading the Holy Quran",
    progress: 0,
    createdAt: new Date(),
    finishDate: new Date(),
    priority: "High",
    status: "in progress",
    category: "religion",
  },
];
